version: '3.5'

services: 
  backend:
    image: backend
    environment: 
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=testuser
      - DB_PASSWORD=testpassw
      - DB_HOST=db
    ports: 
      - 8000:8000
    volumes: 
      - type: bind
        source: ./logs.txt
        target: /usr/app/logs.txt
    depends_on: 
      - db
    container_name: backend
  frontend:
    image: front
    ports: 
      - 5000:5000
    container_name: frontend
  redis:
    image: redis
    ports: 
      - 6379:6379
    container_name: redis
  db:
    image: postgres
    environment: 
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassw
    volumes: 
      - ./database:/var/lib/postgresql/data
    container_name: db